### ISSUE TITLE
bundle fails on c9

### ISSUE THREAD

**Issue by tansaku** [saasbook/typo#19]
```
Installing ruby_core_source 0.1.5

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/local/rvm/rubies/ruby-1.9.3-p551/bin/ruby -r ./siteconf20160119-877-jc0alw.rb extconf.rb 
checking for vm_core.h... no
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/ruby_core_source-0.1.5/lib/ruby_core_source.rb:39: Use RbConfig instead of obsolete and deprecated Config.
checking for vm_core.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/rvm/rubies/ruby-1.9.3-p551/bin/ruby
        --with-ruby-dir
        --without-ruby-dir
        --with-ruby-include
        --without-ruby-include=${ruby-dir}/include
        --with-ruby-lib
        --without-ruby-lib=${ruby-dir}/lib
/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:708:in `remove_entry_secure': parent directory is world writable, FileUtils#remove_entry_secure does not work; abort: "/tmp/d20160119-4177-16affvs" (parent directory mode 40777) (ArgumentError)
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tmpdir.rb:85:in `mktmpdir'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/ruby_core_source-0.1.5/lib/ruby_core_source.rb:60:in `block in create_makefile_with_core'
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/tempfile.rb:320:in `open'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/ruby_core_source-0.1.5/lib/ruby_core_source.rb:51:in `create_makefile_with_core'
        from extconf.rb:19:in `<main>'
Requesting http://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-p551.tar.gz
Downloading http://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-p551.tar.gz

extconf failed, exit code 1

Gem files will remain installed in /usr/local/rvm/gems/ruby-1.9.3-p551/gems/linecache19-0.5.12 for inspection.
Results logged to /usr/local/rvm/gems/ruby-1.9.3-p551/extensions/x86_64-linux/1.9.1/linecache19-0.5.12/gem_make.out
An error occurred while installing linecache19 (0.5.12), and Bundler cannot continue.
Make sure that `gem install linecache19 -v '0.5.12'` succeeds before bundling.
```

thinking this might be related to old ruby debug, see http://stackoverflow.com/questions/18899822/unable-to-complete-bundle-install-unable-to-install-linecache19-v-0-5-12

**Comment by tansaku** [comment]
can fix this by removing ruby-debug from the gemfile

**Comment by dcorking** [comment]
Looks like breakage in the debugger configure script, (specifically in the `ruby_core_source-0.1.5` gem). I guess from a teaching point of view the debugger needs to be in there. I suggest two steps.
1. switch  `gem ruby-debug` to `gem debugger`. If that doesn't work,
2. we need someone with a bit of background in compiling C on unix to look at this.
